algolia/algoliasearch-client-android

- algoliasearch/src/main/AndroidManifest.xml
https://code.google.com/p/android/issues/detail?id=70073
cc @redox
> Remove allowBackup, fix #20

- algoliasearch/src/main/java/com/algolia/search/saas/BaseAPIClient.java
Stop using the DefautHttpClient as [recommanded](http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client), fixing #24. 
@redox: LGTY?
> Refactoring with HTTPUrlConnexion

- algoliasearch/src/main/java/com/algolia/search/saas/BaseAPIClient.java
- algoliasearch/src/main/java/com/algolia/search/saas/BaseIndex.java
- algoliasearch/src/main/java/com/algolia/search/saas/Index.java
- Exposed `Index.searchSync()` to search an Index synchronously, fixing #21.
- Raw methods have been exposed as protected for internal manipulation of request's raw bytes.
@clement-leprovost-algolia: Does this look good to you?
> Synchronous search interface

- algoliasearch/src/main/java/com/algolia/search/saas/BaseIndex.java
- algoliasearch/src/main/java/com/algolia/search/saas/Query.java
Implements variadic (`String...`) interface to allow `new Query("jim").setFacets("*")`, as described [in our documentation](https://www.algolia.com/doc/android#query-json-answer).
- Linkified documentation to ease navigation
- Removed some trailing whitespace
> Query: Updated API to accept String or String[] arguments

- algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java
- algoliasearch/src/test/java/com/algolia/search/saas/PowerMockTestCase.java
- Added test for successful SNI handling
- Added test for effective host switch
> Index: Developed tests using PowerMock

- algoliasearch/src/main/java/com/algolia/search/saas/BaseAPIClient.java
- algoliasearch/src/main/java/com/algolia/search/saas/ExpiringCache.java
Replay of #35 as it has disappeared in the merge.
> Cache: Implemented expiring LRU caching, disabled by default

- algoliasearch/build.gradle
- build.gradle
- release.sh
> Release: Automated via script

- algoliasearch/src/main/java/com/algolia/search/saas/BaseAPIClient.java
Cleaner handling of errors in the ApiClient's requests:
- If a non fatal error is triggered, continue to the next host 
- If a fatal error is encountered, wrap it in AlgoliaException and throw
> ApiClient: Simplified error handling

- algoliasearch/src/main/java/com/algolia/search/saas/Client.java
> Shuffle host array at client init time

- algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java
Added a testcase ensuring we switch to the next host in a reasonable time when facing a DNS timeout.
> Test: Ensuring graceful DNS timeout handling

- algoliasearch/src/main/java/com/algolia/search/saas/Index.java
> Index: Expose forwardToSlaves on setSettings

- algoliasearch/src/main/java/com/algolia/search/saas/Query.java
- algoliasearch/src/test/java/com/algolia/search/saas/QueryTest.java
> Query: Implement aroundRadius=all

- algoliasearch/src/main/java/com/algolia/search/saas/Client.java
See [documentation](https://www.algolia.com/doc/rest#query-multiple-indexes).
> Client: Correct usage of strategy in multipleQueries

- algoliasearch/src/main/java/com/algolia/search/saas/Client.java
- algoliasearch/src/main/java/com/algolia/search/saas/Index.java
- algoliasearch/src/main/java/com/algolia/search/saas/Query.java
After checking all nullability annotations and every comment mentioning a `Nullable` or `NonNull` parameter, this PR corrects found inconsistencies.
> @Nullable/NotNull: Ensure consistency with documentation (#130)

- algoliasearch/src/main/java/com/algolia/search/saas/Index.java
- algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java
> implement getObjects with attributesToRetrieve

- ChangeLog.md
- README.md
- algoliasearch/src/main/java/com/algolia/search/saas/Index.java
Renamed everywhere but in `ChangeLog.md`.
> Rename slaves to replicas

- algoliasearch/src/main/java/com/algolia/search/saas/Index.java
- algoliasearch/src/test/java/com/algolia/search/saas/AssertCompletionHandler.java
- algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java
NOTE: Also contains an improvement on `AssertCompletionHandler`.
> Support `createIfNotExists` parameter in partial updates

- algoliasearch/src/main/java/com/algolia/search/saas/AbstractClient.java
- algoliasearch/src/main/java/com/algolia/search/saas/AbstractQuery.java
- algoliasearch/src/main/java/com/algolia/search/saas/Client.java
- algoliasearch/src/main/java/com/algolia/search/saas/Index.java
- algoliasearch/src/main/java/com/algolia/search/saas/Query.java
- algoliasearch/src/main/java/com/algolia/search/saas/places/PlacesClient.java
- algoliasearch/src/main/java/com/algolia/search/saas/places/PlacesQuery.java
- algoliasearch/src/offline/java/com/algolia/search/saas/MirroredIndex.java
- algoliasearch/src/offline/java/com/algolia/search/saas/OfflineClient.java
- algoliasearch/src/offline/java/com/algolia/search/saas/OfflineIndex.java
- algoliasearch/src/test/java/com/algolia/search/saas/AssertCompletionHandler.java
- algoliasearch/src/test/java/com/algolia/search/saas/Helpers.java
- algoliasearch/src/test/java/com/algolia/search/saas/places/PlacesClientTest.java
- algoliasearch/src/test/java/com/algolia/search/saas/places/PlacesQueryTest.java
- setup_tests.sh
- tools/update-version.sh
This PR adds support for the Places endpoint through a new client (`PlacesClient`) and the associated query class (`PlacesQuery`).
Fixes #175.
> Add support for Algolia Places

- algoliasearch/src/main/java/com/algolia/search/saas/Query.java
Deprecate `setFacetFilters` and `getFacetFilters`, recommending to use respectively `setFilters` and `getFilters` instead.
> Deprecate `facetFilters` in favor of `filter`

- .travis.yml
Use [container based, sudo-enabled](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments) infrastructure.
> Travis: use Precise infrastructure and update Build Matrix

- algoliasearch/common.gradle
- algoliasearch/src/main/java/com/algolia/search/saas/Query.java
- Mark  `Query#setNumericFilters` as deprecated in favor of `setFilters`
- Add `@Nonnull`/`@Nullable`
> Query maintenance

- algoliasearch/src/main/java/com/algolia/search/saas/Query.java
- algoliasearch/src/test/java/com/algolia/search/saas/QueryTest.java
Update `{set,get}InsidePolygon` to handle one or several polygons.
> Query: Migrate insidePolygon to handle several polygons, update insideBoundingBox documentation

- algoliasearch/src/main/java/com/algolia/search/saas/Index.java
- algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java
Implement the new `deleteBy` endpoint.
> Feat deleteBy method

- algoliasearch/src/main/java/com/algolia/search/saas/AbstractClient.java
Fix regression from [ab0a8d](https://github.com/algolia/algoliasearch-client-android/commit/ab0a8d).
> fix(AbstractClient): Accept gzip Encoding

- algoliasearch/src/main/java/com/algolia/search/saas/Index.java
- algoliasearch/src/main/java/com/algolia/search/saas/helpers/DisjunctiveFaceting.java
> refactor: Use Iterable instead of List

- algoliasearch/src/main/java/com/algolia/search/saas/Query.java
- algoliasearch/src/test/java/com/algolia/search/saas/QueryTest.java
Adds the missing parameters reported in algolia/algoliasearch-client-swift#557.
> feat(Query): Implement optionalFilters/sumOrFiltersScores

- algoliasearch/src/main/java/com/algolia/search/saas/Query.java
- algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java
- algoliasearch/src/test/java/com/algolia/search/saas/QueryTest.java
> feat(clickAnalytics): Add clickAnalytics feature

- algoliasearch/common.gradle
Fixes #556 by downgrading to latest stable version.
> fix(dependencies): Downgrade appcompat from 28-beta01 to 27.1.1

- algoliasearch/src/main/java/com/algolia/search/saas/AbstractClient.java
- algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java
- fastlane/Fastfile
- release.sh
Apply final deployment process from [instantsearch-android](https://github.com/algolia/instantsearch-android) to the client.
> chore: Revert WIP Commit, Fastlane PR Deploy Workflow

- CHANGELOG.md
- algoliasearch/common.gradle
Please check the files before merging in case I've overidden something accidentally.
> chore(release): Version 3.27.0 [ci skip]

- README.md
Add a note about considering using Kotlin client instead of the Android client.
> chore: add Kotlin client note in the readme
