algolia/algoliasearch-client-android

algoliasearch/src/androidTest/java/com/algolia/search/saas/ApplicationTest.java

If an assertion fails, we will know why! 
This will really be useful with #33.

AndroidTest: Explicit messages on test failure

---

gradle.properties

Before:
> Running 20 times `./gradlew clean build`...
> Average run time: **11.30 secs**; standard deviation: **1.33 secs**
----
After:
> Running 20 times `./gradlew clean build`...
> Average run time: **8.11 secs**; standard deviation: **0.78 secs**
Build is now **28%** faster.

gradle: Specified properties to speed-up build

---

algoliasearch/src/main/java/com/algolia/search/saas/BaseAPIClient.java
algoliasearch/src/main/java/com/algolia/search/saas/ExpiringCache.java

The cache can be enabled as such:
- `apiClient.enableCache()` caches results for 120 seconds up to a maximum of 64 requests
- `apiClient.enableCache(X, Y)` caches results for X seconds up to a maximum of Y requests

Cache: Implemented expiring LRU caching, disabled by default

---

.travis.yml

Using `travis_retry` to avoid intermittent network issues, as advised by Travis in their [blogpost about network build errors](https://blog.travis-ci.com/2013-05-20-network-timeouts-build-retries/).
If those errors happen regularly, it is probably worth reaching out to Travis team to see if they have a better solution.

Tests: Retrying on failure to avoid "Unable to resolve host"

---

.travis.yml
update_sdk.sh

Updates to our travis config to run parallel builds on different android versions, addressing #26.
- Build Matrix: builds at the same time on the five most frequent android versions
- Travis Cache: stores Gradle caches in Travis to avoid starting from scratch on each build

Build on multiple Android versions

---

setup_tests.sh
teardown_tests.sh

Fixed a forgotten reference to androidTest, allowing again `./setup_tests.sh` and `./teardown_tests.sh` to manually setup and teardown `Helper.java` when running tests locally.

Tests: Specified unitTest Helper file in scripts

---

algoliasearch/build.gradle
algoliasearch/src/main/java/com/algolia/search/saas/ExpiringCache.java

Reduced `minSdkVersion` to the lowest version we can accept (we can't get under 7 without dropping AppCompat).

App: MinSDKVersion lowered to 7

---

algoliasearch/build.gradle
build.gradle

This fixes a build error introduced by the recommended way to configure nexusStaging. 
See Codearte/gradle-nexus-staging-plugin#16 if you want more details.

Fix "Could not find method nexusStaging()"

---

.travis.yml

Fixed failing build by updating tools. Also targeting API 23 as it is *finally* available in Travis.

Travis: Updated build-tools, targeting API 23 instead of 22

---

algoliasearch/src/androidTest/java/com/algolia/search/saas/ApplicationTest.java
algoliasearch/src/main/java/com/algolia/search/saas/Query.java
algoliasearch/src/test/java/com/algolia/search/saas/QueryTest.java

The `Query` class now provides untyped accessors to a dictionary of extra parameters. Those parameters are appended to the query string after all the typed parameters. This allows using query parameters not supported by the current version of the API client.
Fixes #66.

Allow extra query parameters to be specified

---

.travis.yml
run_test.sh

Using `travis_retry` only on `gradle` call to avoid unnecessary repeated setup/teardown.

Travis: Narrower retry use (only on gradle task)

---

run_test.sh

As travis functions are unavailable in subshell, including [source code](https://github.com/travis-ci/travis-build/blob/73f74a94957f73eb54dc821f80c0c85ad8f8aab7/lib/travis/build/script/templates/header.sh#L168-L187) as [recommended](https://twitter.com/plexus/status/499194992632811520).

Travis: Defining travis_retry if missing

---

algoliasearch/android-release-jar.gradle
run_test.sh

Changed gradle release script to use `nexus{Username,Password}` instead of `ossrh[...]`, which is the naming used in [gradle-nexus-staging-plugin](/Codearte/gradle-nexus-staging-plugin) and [gradle-nexus-plugin](/bmuschko/gradle-nexus-plugin). 
This simplifies `local.properties` by avoiding repeated values for different property names.
PS: Please ignore the change to `run_test.sh`: babf6b6 was cherry-picked to fix travis build, and is already in [v3](v3).

Unify properties names

---

algoliasearch/src/main/java/com/algolia/search/saas/BaseAPIClient.java

Fixed NPE due to the creation of an `InputStreamReader` directly on `getErrorStream()`, which [can return null](http://download.java.net/jdk7/archive/b123/docs/api/java/net/HttpURLConnection.html#getErrorStream%28%29).

Client: Fixed stream being read when null

---

algoliasearch/src/main/java/com/algolia/search/saas/Query.java
algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java
algoliasearch/src/test/java/com/algolia/search/saas/QueryTest.java

The rationale for not implementing them was that they cannot be adequately typed. However, after investigation:
- `numericFilters` has roughly the same complexity as `tagFilters` or `facetFilters`. Therefore using a JSON array type, like for those parameters, should be adequate (although suboptimal).
- `filters` is designed to be a “SQL-like notation”, so I guess a raw string type is adequate. In the future, we may want to provide tools to build the filters more easily, but this will likely come in the form of “helpers”, as it is done in the Javascript client.
Since the absence of typed accessors for the missing parameters was confusing, I am adding them now.

Add missing query parameters `filters` and `numericFilters`

---

algoliasearch/src/main/java/com/algolia/search/saas/Client.java

We are already using a plain `HttpURLConnection`, but the handling of POST request bodies was still done using Apache’s classes. This commit switches to plain built-in classes.
*Note: Apache HTTP client will be removed in Android N, so we need to drop it to remain compatible.*

Remove any dependency to Apache HTTP client

---

algoliasearch/src/main/java/com/algolia/search/saas/Client.java
algoliasearch/src/offline/java/com/algolia/search/saas/OfflineClient.java
algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java

- Expose it as a structured list of library versions.
- Migrate to new format (semicolon-separated with parentheses).
- Add operating system’s version to the list.
Fixes #121.

Improve handling of `User-Agent` header

---

algoliasearch/common.gradle
algoliasearch/src/test/java/com/algolia/search/saas/AssertCompletionHandler.java
algoliasearch/src/test/java/com/algolia/search/saas/BrowseIteratorTest.java
algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java

The previous way of writing tests with `CountDownLatch` had the drawback of silencing inner `AssertionErrors`: when an assertion failed in a callback, the only information given was that all callbacks did not complete.
This PR improves this setup by wrapping each `CompletionHandler` in a `AssertCompletionHandler`: any `AssertionError` thrown inside the handler is picked up by the wrapper and will eventually be rethrown in `checkAssertions()`. 
Likewise, the tests in *BrowseIteratorTest* have been rewritten with a `AssertBrowseHandler` wrapper.

Tests: Refactor to expose inner AssertionErrors

---

ChangeLog.md
algoliasearch/src/main/java/com/algolia/search/saas/Query.java

This allows to reuse the parsing method when manipulating search results, avoiding [duplicated code in instantsearch-android](https://github.com/algolia/instantsearch-android/blob/master/instantsearch/src/main/java/com/algolia/instantsearch/model/SearchResults.java#L152-L166).

Query: Expose parseLatLng method

---

algoliasearch/src/main/java/com/algolia/search/saas/Client.java
algoliasearch/src/offline/java/com/algolia/search/saas/OfflineClient.java
algoliasearch/src/test/java/com/algolia/search/saas/ClientTest.java

Each `Client` keeps a map of already created indices, with the index name as the key and a weak reference to the index as a value. When asked for an index with the same name, it returns the already created one, unless it has been garbage-collected.
NOTE: In the tests, running the garbage collector does not finalize the index, although it ought to work (it does on a simple example). However, the debugger is positive that the only reference to the object is the weak map. => We’ll assume it should work in the real world… :/

Share `Index` instances

---

algoliasearch/src/main/java/com/algolia/search/saas/Query.java

NOTE: This is a build-time parameter, so it is not implemented in the `Query` class. However, it is mentioned in some parts of the documentation.
WARNING: Wait for the new parameter to be implemented before merging!

Rename `attributesToIndex` to `searchableAttributes`

---

ChangeLog.md
algoliasearch/src/main/java/com/algolia/search/saas/Query.java
algoliasearch/src/test/java/com/algolia/search/saas/QueryTest.java

Implement `ignorePlurals` as list of language codes.
You can now set this parameter using:
- `Query.setIgnorePlurals(true)` to enable the feature on all supported languages.
- `Query.setIgnorePlurals("en", "fr")` to select languages via one or several Strings (or a String array).
- `Query.setIgnorePlurals(Arrays.asList("en", "fr"))` to select languages via a `Collection` of Strings.

ignorePlurals: Also accept list of language ISO codes

---

algoliasearch/src/test/java/com/algolia/search/saas/BrowseIteratorTest.java
algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java
algoliasearch/src/test/java/com/algolia/search/saas/QueryTest.java
algoliasearch/src/test/java/com/algolia/search/saas/places/PlacesClientTest.java
algoliasearch/src/test/java/com/algolia/search/saas/places/PlacesQueryTest.java

- Correct usage of `assert{,Array,Not}Equals`: most of the time `expected` and `equals` were inverted, **which produced misleading assert messages** (`expected "error" but got "valid"`).
- Check `Query.get(KEY)` for all tests, almost half were untested
- Check against `query1`'s content and not hardcoded value in analyticsTags (like we do in other tests)
- Use `getIndex` instead of deprecated `initIndex`
- Use `String.contains` instead of `RegExp.match` to get the performance of the former when we don't need the powerfulness of the latter
- Use `Integer.valueOf()` instead of `new Integer()` to avoid creating multiple instances of same value
- Use `Collections.singletonList` instead of `Arrays.asList` when parameter is single value
- Remove unnecessary `test`/`test_` prefixes
- Inline …

Cleanup tests

---

algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java

- Test only one successful query but not empty string
- Test DNS timeout correctly

Fix IndexTest.searchAync and IndexTest.DNSTimeout

---

algoliasearch/src/main/java/com/algolia/search/saas/Index.java
algoliasearch/src/offline/java/com/algolia/search/saas/BootstrapListener.java
algoliasearch/src/offline/java/com/algolia/search/saas/BuildListener.java
algoliasearch/src/offline/java/com/algolia/search/saas/FileUtils.java
algoliasearch/src/offline/java/com/algolia/search/saas/MirroredIndex.java
algoliasearch/src/offline/java/com/algolia/search/saas/OfflineIndex.java
algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java
algoliasearch/src/testOffline/java/com/algolia/search/saas/MirroredIndexTest.java
algoliasearch/src/testOffline/java/com/algolia/search/saas/OfflineIndexTest.java
algoliasearch/src/testOffline/res/raw/objects.json
algoliasearch/src/testOffline/res/raw/settings.json

- Manually build a `MirroredIndex` or an `OfflineIndex` from local files or raw resources. Combined with a new `hasOfflineData()` getter, this allows **bootstrapping** a mirrored index before the first sync.
- Get individual objects directly from the local mirror of a `MirroredIndex`, or use the same fallback policy as search.

New offline features

---

algoliasearch/build-offline.gradle
algoliasearch/src/main/java/com/algolia/search/saas/Index.java
algoliasearch/src/offline/java/com/algolia/search/saas/MirroredIndex.java
algoliasearch/src/offline/java/com/algolia/search/saas/OfflineIndex.java
algoliasearch/src/testOffline/java/com/algolia/search/saas/MirroredIndexTest.java
algoliasearch/src/testOffline/java/com/algolia/search/saas/OfflineIndexTest.java
algoliasearch/src/testOffline/java/com/algolia/search/saas/OfflineTestBase.java

Implement offline search for facet values, just like for regular search:
- on `MirroredIndex` with request strategy
- on `OfflineIndex` for pure offline request
Requires Offline Core 1.1.0, which is out now.

Support offline search for facet values

---

algoliasearch/src/main/java/com/algolia/search/saas/AbstractClient.java
algoliasearch/src/test/java/com/algolia/search/saas/Helpers.java
algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java

When the header of the request is too big, we get a 494 header too large error. 
The header becomes too large when we generate a very large secure api key that is mixed with query parameters. 
A temporary fix is to put the apikey in the body instead of the header for search requests

Fix the case when header is bigger than 8KB

---

algoliasearch/src/main/java/com/algolia/search/saas/places/PlacesClient.java
algoliasearch/src/test/java/com/algolia/search/saas/places/PlacesClientTest.java

Solves #389 (as #388 is blocked waiting, I'll handle the eventual merge conflict on `getRequest`'s usage).

feat(PlacesClient): GetByObjectID

---

algoliasearch/src/main/java/com/algolia/search/saas/Index.java
algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java

Deprecate waitTask(int) as taskIDs are not guaranteed to be integers:
> leo: They should always be _numeric values_, but I would guess they are 64bits values not 32bits values
@spinach: Do you think this is a case where we should introduce a "breaking" change? (If waitTask(int) will anyway error at runtime, should we remove it to trigger the error at compile time?)

fix(waitTask): Deprecate broken waitTask(int)

---

algoliasearch/src/main/java/com/algolia/search/saas/Index.java

When waiting for a task, we multiply the waiting time *=2 . After the limit, the long will overflow to negative and so, Thread.sleep will throw an exception

Fix waitTask overflow

---

algoliasearch/src/main/java/com/algolia/search/saas/Query.java
algoliasearch/src/test/java/com/algolia/search/saas/QueryTest.java

This refactors the `Query` parameters using enums, to give each value a specific `toString()` and use it in the getters and setters. As there is no equivalent to `#valueOf()` to return an enum value from its String representation, I added a `#fromString()` method to each one.

Refactor Query's Enums

---

algoliasearch/src/main/java/com/algolia/search/saas/Index.java

Following a [support ticket](https://secure.helpscout.net/conversation/565782059/59333/?folderId=1106255) wondering why one cannot `setSettings` but only `setSettingsAsync`.
The original author on these methods' access modifiers:
> Not sure… I think it’s just that Android forbids network requests from the main thread, so we didn’t want to expose a public method that would fail when used from there. Honestly, I don’t mind if we make it public.
To enable our users to do sync processing when it makes sense (e.g. from a background thread), this PR exposes our sync methods. 
I believe we don't need to put a specific warning in every method: it's a standard in Android not to call sync methods from the main thread, developers know how to solve a [NetworkOnMainThread …

feat(Index): Expose sync methods

---

algoliasearch/src/main/java/com/algolia/search/saas/Query.java
algoliasearch/src/main/java/com/algolia/search/saas/places/PlacesQuery.java

Don't require to wrap a `CharSequence` with a `String` to `setQuery`.

fix(Query): Accept any CharSequence

---

algoliasearch/src/main/java/com/algolia/search/saas/Query.java
algoliasearch/src/test/java/com/algolia/search/saas/QueryTest.java
build.gradle

**Summary**
Exposes `enablePersonalization` as a typed `Query` attribute.
**Result**
`fastlane test` -> :ok_hand:

feat(Query): enablePersonalization

---

.github/PULL_REQUEST_TEMPLATE.md
algoliasearch/src/test/java/com/algolia/search/saas/IndexTest.java
fastlane/Fastfile

**Summary**
Expose URL using `envman`, required for use in next Bitrise steps. 
**Result**
Will be demonstrated with next release.

chore: Expose PR URL, improve PR_TEMPLATE, disable flaky test
